#!/bin/bash
#PBS -N nf_medip_medips
#PBS -q long
#PBS -l select=1:ncpus=2:mem=8gb
#PBS -l walltime=96:00:00
#PBS -o logs/nf_medip_medips.out
#PBS -e logs/nf_medip_medips.err

cd "$PBS_O_WORKDIR"
mkdir -p logs
mkdir -p tmp

source /home/shangying/miniconda3/bin/activate medip-nf
export PATH="/home/shangying/miniconda3/bin:$PATH"
export TMPDIR="$PBS_O_WORKDIR/tmp"
export TEMP="$TMPDIR"
export TMP="$TMPDIR"
module load singularity/4.2.1

nextflow run . \
  -profile hpc_singularity \
  --input test_data/samplesheet.csv \
  --fasta /projects/sychen/projects/patnsb/ebv_kd_medip/ref/GRCh38.p14.genome.fa \
  --outdir results/fastq_to_bam_test \
  --analysis_method medips \
  --analysis_mode dmr \
  --contrast KD,control \
  -resume
